name: Build and Deploy

on:
  push:
    branches:
      - master # 你可以根据需要更改分支名称
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone to Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 请根据你的项目需求选择 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: './.vitepress/dist/'
          target: /var/www/html/z-doc
          debug: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vitepress/dist
